import { describe, it, expect } from "vitest";
import { routeEdgeOrthogonal } from "../../src/layout";
import { Point } from "../../src/model";

function segmentsOverlap(pathA: readonly Point[], pathB: readonly Point[]): boolean {
  for (let i = 1; i < pathA.length; i++) {
    const a1 = pathA[i - 1];
    const a2 = pathA[i];

    for (let j = 1; j < pathB.length; j++) {
      const b1 = pathB[j - 1];
      const b2 = pathB[j];

      // The user explicitly requested horizontal edge segments to not touch.
      // Vertical segments originating from staggered source ports may run close
      // to each other as they drop down, which is expected orthogonal behavior
      // around dense port hubs.

      if (a1.y === a2.y && b1.y === b2.y) {
        if (Math.abs(a1.y - b1.y) < 10) {
          const aMin = Math.min(a1.x, a2.x);
          const aMax = Math.max(a1.x, a2.x);
          const bMin = Math.min(b1.x, b2.x);
          const bMax = Math.max(b1.x, b2.x);
          if (Math.max(aMin, bMin) <= Math.min(aMax, bMax)) {
            return true;
          }
        }
      }
    }
  }
  return false;
}

describe("Horizontal Routing Boundary", () => {
  it("Horizontal Alignment Non-Overlap Property: Paths to horizontally aligned children do not perfectly overlap", () => {
    const parentId = "parent";

    const layout = {
      positions: new Map([
        [parentId, { x: 0, y: 0 }],
        ["child1", { x: 50, y: 50 }],
        ["child2", { x: 150, y: 50 }],
        ["child3", { x: 250, y: 50 }]
      ]),
      nodeSizes: new Map([
        [parentId, { width: 350, height: 150 }],
        ["child1", { width: 50, height: 50 }],
        ["child2", { width: 50, height: 50 }],
        ["child3", { width: 50, height: 50 }]
      ]),
      hierarchy: new Map([
        [parentId, { children: ["child1", "child2", "child3"], parent: null }],
        ["child1", { children: [], parent: parentId }],
        ["child2", { children: [], parent: parentId }],
        ["child3", { children: [], parent: parentId }]
      ]),
      nodeSize: { width: 100, height: 50 },
      width: 500,
      height: 500
    } as any;

    // Simulate staggered source points as generated by edgeEndpoints in layout.ts
    const spacing = 16;
    const sourcePt1 = { x: 150 + (0 - 1) * spacing, y: -100 };
    const sourcePt2 = { x: 150 + (1 - 1) * spacing, y: -100 };
    const sourcePt3 = { x: 150 + (2 - 1) * spacing, y: -100 };

    const targetPt1 = { x: 75, y: 50 }; // Top edge of child1
    const targetPt2 = { x: 175, y: 50 }; // Top edge of child2
    const targetPt3 = { x: 275, y: 50 }; // Top edge of child3

    const path1 = routeEdgeOrthogonal(sourcePt1, targetPt1, layout, 0, 0, 3, 1);
    const path2 = routeEdgeOrthogonal(sourcePt2, targetPt2, layout, 1, 0, 3, 1);
    const path3 = routeEdgeOrthogonal(sourcePt3, targetPt3, layout, 2, 0, 3, 1);

    expect(path1.length).toBeGreaterThan(0);
    expect(path2.length).toBeGreaterThan(0);
    expect(path3.length).toBeGreaterThan(0);

    const overlap12 = segmentsOverlap(path1, path2);
    const overlap23 = segmentsOverlap(path2, path3);
    const overlap13 = segmentsOverlap(path1, path3);

    expect(overlap12).toBe(false);
    expect(overlap23).toBe(false);
    expect(overlap13).toBe(false);
  });
});
